name: resturant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  dartx: ^1.2.0
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  fluttertoast: ^8.2.8
  flutter_rating_bar: ^4.0.1
  gap: ^3.0.1
  http: ^0.13.4
  get: ^4.6.6
  supabase_flutter: ^2.8.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
